### ISSUE TITLE
Comprobar la corrección del código

### ISSUE THREAD

**Issue by soyjorgeprg** [soyjorgeprg/macime#16]
* Decidir cuál es el marco de pruebas idóneo
* Decidir cuál es la mejor biblioteca de aserciones
* Implementar las pruebas necesarias para el funcionamiento correcto

Relación con la HU01 #4 ya que queremos que el código sea funcional

**Comment by JJ** [comment]
Asegurar la corrección del código hay que hacerlo siempre y en relación a todas las HUs. De esto puede salir cualquier cosa.
