### ISSUE TITLE
Creación de la estructura mínima para el desarrollo del aplicativo

### ISSUE THREAD

**Issue by soyjorgeprg** [soyjorgeprg/macime#8]
Comenzaremos el desarrollo de nuestro aplicativo mediante la creación de las clases mínimas para su correcto desarrollo. 

[Relacionado con la US #4]

**Comment by JJ** [comment]
Esto no puede ser un issue, porque no plantea un problema.

**Comment by soyjorgeprg** [comment]
@JJ he actualizado el issue para que ahora si sea un problema real al que me enfrento como desarrollador
